# Generated by Django 2.1.7 on 2019-02-24 09:44

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hrmgmt', '0002_auto_20190224_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='parent',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='hrmgmt.Employee'),
        ),
    ]
