# Generated by Django 2.2.6 on 2019-10-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmgmt', '0007_auto_20190224_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
