# Generated by Django 2.1.7 on 2019-02-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmgmt', '0003_auto_20190224_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.CharField(choices=[('STD', 'base employee'), ('UPP', 'upper employee'), ('MGR', 'manager'), ('SRMGR', 'senior manager'), ('CEO', 'president')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('STD', 'base employee'), ('UPP', 'upper employee'), ('MGR', 'manager'), ('SRMGR', 'senior manager'), ('CEO', 'president')], max_length=25),
        ),
    ]
