# Generated by Django 2.1.7 on 2019-02-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmgmt', '0004_auto_20190224_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.CharField(choices=[('STD', 500), ('UPP', 700), ('MGR', 1000), ('SRMGR', 1200), ('CEO', 1500)], max_length=25, null=True),
        ),
    ]
