# Generated by Django 2.1.7 on 2019-02-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmgmt', '0006_auto_20190224_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
